import Head from "next/head";
import { useState, useEffect } from "react";
import clsx from "clsx";
import { InputField } from "@/components/inputField";
import { Header } from "@/containers/Header";
import { FontType } from "@/containers/Header";

export default function Home() {
  const [isDarkTheme, setIsDarkTheme] = useState(true);
  const [font, setFont] = useState<FontType>(FontType.INTER);
  const [textColor, setTextColor] = useState<"text-white" | "text-black">(
    "text-white"
  );
  const [backgroundColor, setBackgroundColor] = useState<
    "bg-white" | "bg-black"
  >("bg-black");

  const toggleTheme = () => {
    setIsDarkTheme(!isDarkTheme);
  };

  const toggleFont = (_font: FontType) => {
    if (_font === FontType.INTER) {
      setFont(FontType.INTER);
    } else if (_font === FontType.LORA) {
      setFont(FontType.LORA);
    } else {
      setFont(FontType.INCONSOLATA);
    }
  };

  useEffect(() => {
    if (!isDarkTheme) {
      setTextColor("text-black");
      setBackgroundColor("bg-white");
    } else {
      setTextColor("text-white");
      setBackgroundColor("bg-black");
    }
  }, [isDarkTheme]);

  return (
    <>
      <Head>
        <title>Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/favicon.png" />
      </Head>
      <main
        className={`w-full h-screen flex justify-center pt-58 ${backgroundColor} ${textColor} ${font} transition-all duration-500 ease-in-out`}
      >
        <div className="max-w-736 w-full">
          <Header
            theme={isDarkTheme ? "dark" : "light"}
            toggleTheme={toggleTheme}
            font={font}
            toggleFont={toggleFont}
          />
        </div>
        {/* <InputField
          value="Some value"
          placeholder="Enter word"
          handleChange={(e) => console.log("somethig")}
        /> */}
      </main>
    </>
  );
}
